# Site
repository: k2khan/k2khan.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Hamad Khan 
title: Software Engineer 
email: hamad.khan@slu.edu
# website: k2khan.github.io 

# Dark Mode (true/false/never)
darkmode: never 

# Social links
# twitter_username: facespics
github_username: k2khan 
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: hamad-khan-04987b164 
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile-pic.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Hamad. I'm currently finishing up my B.S. in computer science w/ a minor in math. 

  I am most skilled in: <mark>Eating Pizza</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Scheme Interpreter 
        link: github.com/k2khan/scheming-in-haskell
        link_text: Link to Project 
        additional_links:
          - title: k2khan/scheming-in-haskell 
            icon: fab fa-github
            url: github.com/k2khan/scheming-in-haskell
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          *Full-fledged scheme interpreter written in Haskell.*
        
          After learning Haskell in my programming languages class, I was intrigued to learn more about Haskell and compilers.

      - layout: left
        title: Clippy
        link: github.com/k2khan/clippy
        link_text: Link to Project
        additional_links:
          - title: k2khan/clippy
            icon: fab fa-github
            url: github.com/k2khan/clippy
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          *"Monopoly" game where you try to take over the world's supply of paperclips*

          Inspired by [Universal Paperclips](https://www.decisionproblem.com/paperclips/index2.html), we built this game as our final project for our software design class.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: U.S. Bank
        sub_title: Software Development Intern
        caption: June 2021 - Aug 2021
        #quote: >
        description: | # this will include new lines to allow paragraphs
          Will have more fun.

      - layout: left
        title: U.S. Bank
        sub_title: Software Development Intern
        caption: June 2020 - Aug 2020 
        #quote: >
        description: | # this will include new lines to allow paragraphs
          Had some fun.


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Saint Louis University
        caption: 2018 - 2022 
        sub_title: B.S. Computer Science, Math Minor
        sub_title: 3.86/4.0 GPA
        #quote: >
        description: | # this will include new lines to allow paragraphs
          SLU is cool.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Running/Lifting
      - Gaming (Dota2/CSGO)

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
